__Let's start by importing PyTorch and checking the version we're using.__

In [1]:
import torch
torch.__version__

'2.13.0+cu132'

Wonderful, it looks like we've got PyTorch 2.13.0+.

This means if you're going through these materials, you'll see most compatability with PyTorch 2.13.0+, however if your version number is far higher than that, you might notice some inconsistencies.

Introduction to tensors
Now we've got PyTorch imported, it's time to learn about tensors.

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

Creating tensors
PyTorch loves tensors. So much so there's a whole documentation page dedicated to the torch.Tensor class. <br>

Let's code.

The first thing we're going to create is a scalar.

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [2]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


Let's code.

The first thing we're going to create is a scalar.

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [3]:
print(type(scalar))

<class 'torch.Tensor'>


We can check the dimensions of a tensor using the ndim attribute.

In [4]:
scalar.ndim

0

What if we wanted to retrieve the number from the tensor?

As in, turn it from torch.Tensor to a Python integer?

To do we can use the item() method.

In [5]:
scalar.item()

7

Okay, now let's see a vector.

A vector is a single dimension tensor but can contain many numbers.

As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

The important trend here is that a vector is flexible in what it can represent (the same with tensors).

In [6]:
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [7]:
vector.ndim

1

Hmm, that's strange, vector contains two numbers but only has a single dimension.

I'll let you in on a trick.

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.

Let's check out the shape of vector.

In [8]:
vector.shape

torch.Size([2])

The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

In [9]:
MATRIX = torch.tensor([
    [7, 8,], [9, 10,]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
#check number of dimensions
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

We get the output torch.Size([2, 2]) because MATRIX is two elements deep and two elements wide.

How about we create a tensor?

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

Random tensors
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using torch.rand() and passing in the size parameter.

In [15]:
torch.manual_seed(42)
rand_tensor = torch.rand(size = (3, 5))
rand_tensor, rand_tensor.dtype

(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
         [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]]),
 torch.float32)

___The above creates data of 3 rows and 5 columns___

In [16]:
rand_img_size = torch.rand(size = (224, 224, 3))

rand_img_size.shape, rand_img_size.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
torch.rand([3, 2, 3], dtype=torch.float16)

tensor([[[0.0992, 0.3079, 0.7788],
         [0.8018, 0.3650, 0.6284]],

        [[0.9663, 0.7686, 0.4565],
         [0.5747, 0.9199, 0.3230]],

        [[0.8613, 0.0919, 0.3103],
         [0.9536, 0.6001, 0.0351]]], dtype=torch.float16)

Zeros and ones
Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with torch.zeros()

Again, the size parameter comes into play.

In [18]:
torch.zeros(0)

tensor([])

In [19]:
torch.zeros(1)

tensor([0.])

In [20]:
torch.zeros(size=[4, 5])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

We can do the same to create a tensor of all ones except using torch.ones() instead

In [21]:
torch.ones(size=[4, 5])

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
torch.ones(0)

tensor([])

In [23]:
torch.ones(1)

tensor([1.])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.



Creating range in pytorch

In [24]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
print(zero_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
ten_zeros = torch.zeros_like(input=zero_to_ten, dtype=torch.int8)

NameError: name 'zero_to_ten' is not defined

In [26]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int8)

In [4]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype = None,
    device = None,
    requires_grad = False # if True, will track gradients for this tensor
 )
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.requires_grad

(torch.Size([3]), torch.float32, device(type='cpu'), False)

In [5]:
float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16, device=None, requires_grad=False)

float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device, float_16_tensor.requires_grad

(torch.Size([3]), torch.float16, device(type='cpu'), False)

#### Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
- shape - what shape is the tensor? (some operations require specific shape rules)
- dtype - what datatype are the elements within the tensor stored in?
- device - what device is the tensor stored on? (usually GPU or CPU)


Let's create a random tensor and find out details about it

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
some_tensor = torch.rand(6, 5, dtype=torch.float16, device = device, requires_grad = True)

print(f"Device: {some_tensor.device}")
print(f"Data type: {some_tensor.dtype}")
print(f"Requires grad: {some_tensor.requires_grad}")

print(some_tensor)

Device: cuda:0
Data type: torch.float16
Requires grad: True
tensor([[0.8086, 0.8042, 0.7505, 0.7700, 0.0578],
        [0.3101, 0.7100, 0.2362, 0.6133, 0.0718],
        [0.5205, 0.6074, 0.7163, 0.0758, 0.7017],
        [0.4417, 0.6787, 0.7935, 0.8198, 0.2856],
        [0.6523, 0.2776, 0.2810, 0.4670, 0.1716],
        [0.2754, 0.9170, 0.6245, 0.5259, 0.0101]], device='cuda:0',
       dtype=torch.float16, requires_grad=True)


#### Manipulating tensors (tensor operations)¶

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors. <br>

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.<br>

These operations are often a wonderful dance between:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.<br>

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).


Basic operations <br>
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

They work just as you think they would.

In [8]:
norm_tensor = torch.tensor([2,3,4], dtype=torch.float32, device=device, requires_grad=True)

norm_tensor + 10

tensor([12., 13., 14.], device='cuda:0', grad_fn=<AddBackward0>)

# Multiply by 10

In [9]:
norm_tensor * 10

tensor([20., 30., 40.], device='cuda:0', grad_fn=<MulBackward0>)

In [10]:
# subtract 10 from the tensor and then add 10 to it
norm_tensor = norm_tensor - 10
norm_tensor = norm_tensor + 10
print(norm_tensor)

tensor([2., 3., 4.], device='cuda:0', grad_fn=<AddBackward0>)


PyTorch also has a bunch of built-in functions like `torch.mul()` (short for multiplication) and `torch.add()` to perform basic operations.

In [11]:
torch.multiply(norm_tensor, 10)

tensor([20., 30., 40.], device='cuda:0', grad_fn=<MulBackward0>)

In [12]:
torch.add(norm_tensor, 10)

tensor([12., 13., 14.], device='cuda:0', grad_fn=<AddBackward0>)

### Matrix multiplication (is all you need)
> One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

> PyTorch implements matrix multiplication functionality in the torch.matmul() method.

> The main two rules for matrix multiplication to remember are:

> 1. The inner dimensions must match:
> - (3, 2) @ (3, 2) won't work
> - (2, 3) @ (3, 2) will work
> - (3, 2) @ (2, 3) will work
> 2. The resulting matrix has the shape of the outer dimensions:
> - (2, 3) @ (3, 2) -> (2, 2)
> - (3, 2) @ (2, 3) -> (3, 3)
> Note: "@" in Python is the symbol for matrix multiplication.

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

In [13]:
tensor = torch.tensor([1, 2, 3])

tensor + 10

tensor([11, 12, 13])

In [14]:
tensor.shape

torch.Size([3])

In [15]:
tensor * tensor

tensor([1, 4, 9])

The difference between element-wise multiplication and matrix multiplication is the addition of values.<br>

For our tensor variable with values [1, 2, 3]:

|Operation|Calculation|Code|
|---------|-----------|---------|
|Element-Wise multiplication|`[1*1, 2*2, 3*3] = [1,4,9]`|tensor * tensor|
|Matrix multiplication|`[1*1 + 2*2 + 3*3] = [14]`|tensor.matmul(tensor)|

In [16]:
tensor @ tensor

tensor(14)

In [17]:
# or 
tensor.matmul(tensor)

tensor(14)

In [20]:
import time

In [23]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)


value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 24.6 ms


In [24]:
%%time

tensor @ tensor

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

##### One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [27]:
tensor_A = torch.tensor([
    [1,2],
    [4,5],
    [7,8]
], dtype=torch.float32)

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
], dtype=torch.float32)

tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [28]:
tensor_A.matmul(tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [29]:
tensor_A.shape

torch.Size([3, 2])

In [30]:
tensor_B.shape

torch.Size([3, 2])

In [31]:
tensor_A.matmul(tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 78.,  87.,  96.],
        [129., 144., 159.]])

In [32]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 78.,  87.,  96.],
        [129., 144., 159.]])

Output shape: torch.Size([3, 3])


You can also use torch.mm() which is a short for torch.matmul().

In [33]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 78.,  87.,  96.],
        [129., 144., 159.]])

Neural networks are full of matrix multiplications and dot products.

The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.


Where: $$ y = x\cdot A^T + b $$

- x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
- A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the `"T"`, that's because the weights matrix gets transposed).
__Note:__ You might also often see W or another letter like X used to showcase the weights matrix.
- b is the bias term used to slightly offset the weights and inputs.
- y is the output (a manipulation of the input in the hopes to discover patterns in it).
This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?

In [36]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=tensor_A.T.shape[0], out_features=6)

x  = tensor_A

output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [5.6194, 2.6809, 0.4347, 0.5995, 0.4447, 3.2247],
        [9.0019, 4.1326, 0.3980, 0.8125, 0.7585, 5.4656]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


Finding the min, max, mean, sum, etc (aggregation)
Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.

In [37]:
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [38]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [39]:
print(F"Minimum value: {x.min()}")
print(F"Maximum value: {x.max()}")
print(F"Mean value: {x.type(torch.float32).mean()}")
print(F"Sum: {x.sum()}")

Minimum value: 0
Maximum value: 90
Mean value: 45.0
Sum: 450


Positional min/max
You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the `softmax activation function`).

In [40]:
tensor = torch.arange(0, 100, 10)

# Return the index of both the minimum and maximum values of a tensor
print(f"minimum value index: {tensor.argmin()}")
print(f"maximum value index: {tensor.argmax()}")

minimum value index: 0
maximum value index: 9


Change tensor datatype
As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

First we'll create a tensor and check its datatype (the default is `torch.float32`).

In [42]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [43]:
tensor_16 = tensor.type(torch.float16)

tensor_16.dtype

torch.float16

And we can do something similar to make a torch.int8 tensor.

In [44]:
tensor_8 = tensor.type(torch.int8)
tensor_8.dtype

torch.int8

Reshaping, stacking, squeezing and unsqueezing <br>
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

In [45]:
tensor_A

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])

In [46]:
torch.reshape(tensor_A, (2, 3))

tensor([[1., 2., 4.],
        [5., 7., 8.]])

In [53]:
torch.reshape(tensor_A, (-1,1))

tensor([[1.],
        [2.],
        [4.],
        [5.],
        [7.],
        [8.]])

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.

In [54]:
x = torch.arange(1., 8.)

x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

In [55]:
x_reshaped = x.reshape(1, 7)

x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [56]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723

z = x.view(1, 7)
print(z, z.shape, z.ndim)

tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7]) 2


In [60]:
z[:, 0:3] = torch.tensor([6.,7.,8.])
z, x 

(tensor([[6., 7., 8., 4., 5., 6., 7.]]), tensor([6., 7., 8., 4., 5., 6., 7.]))